configure python fixes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -658,11 +658,11 @@ ac_ct_CC
 EXEEXT
 OBJEXT
 LN_S
-HAS_INSTALLX
 DO_MAS_DRIVER
 DRIVER_BIGPHYS
 DRIVER_FAKEMCE
 KERNEL_DIR
+PYTHON_DIR
 DO_MAS_SWIG
 MAS_USER
 MAS_GROUP
@@ -1256,8 +1256,9 @@ Optional Packages:
   --without-bigphysarea   disable bigphysarea
   --with-fakemce          enable fakemce
   --with-kernel-dir       set the target kernel source tree (e.g. $KERNEL_DIR)
-  --with-python=(yes|no)  enable/disable swig/python compilation and
-                          installation
+  --with-python=(PATH|yes|no)
+                          enable/disable swig/python compilation and
+                          installation, PATH default is $PYTHON_DIR
   --with-user=LOGIN       set default MAS user
   --with-group=GROUP      set default MAS group
   --with-prefix=PATH      set default MAS install location, e.g. /usr/mce
@@ -2629,45 +2630,6 @@ else
 echo "${ECHO_T}no, using $LN_S" >&6; }
 fi
 
-# Extract the first word of "install", so it can be a program name with args.
-set dummy install; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_prog_HAS_INSTALLX+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$HAS_INSTALLX"; then
-  ac_cv_prog_HAS_INSTALLX="$HAS_INSTALLX" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_HAS_INSTALLX="yes"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  test -z "$ac_cv_prog_HAS_INSTALLX" && ac_cv_prog_HAS_INSTALLX="no"
-fi
-fi
-HAS_INSTALLX=$ac_cv_prog_HAS_INSTALLX
-if test -n "$HAS_INSTALLX"; then
-  { echo "$as_me:$LINENO: result: $HAS_INSTALLX" >&5
-echo "${ECHO_T}$HAS_INSTALLX" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-test "$HAS_INSTALLX" = yes && fail=:
 
 
 # Allow the user to suppress driver compile / install.
@@ -2717,18 +2679,21 @@ fi
 
 
 
+# Allow the user to suppress/relocate swig/python compile/install
 
+PYTHON_DIR=/usr/include/python2.5/
 
 # Check whether --with-python was given.
 if test "${with_python+set}" = set; then
-  withval=$with_python; DO_MAS_SWIG=$withval
-else
-  DO_MAS_SWIG=yes
+  withval=$with_python; PYTHON_DIR=$withval
 fi
 
 
+DO_MAS_SWIG=yes
+test "$PYTHON_DIR" = "no" && DO_MAS_SWIG=no
 
 
+# MAS user and group are configurable
 
 
 # Check whether --with-user was given.
@@ -2750,6 +2715,7 @@ fi
 
 
 
+# MAS install path is configurable
 
 
 # Check whether --with-prefix was given.
@@ -2762,6 +2728,7 @@ fi
 
 
 
+# The location of libconfig is configurable.  libconfigurable.
 
 
 # Check whether --with-libconfig was given.
@@ -2780,6 +2747,7 @@ LIBCONFIG_ARGS="$LIBCONFIG_ARGS -lconfig"
 
 
 
+# Check for libconfig.
 
 
 
@@ -2861,6 +2829,7 @@ fi
 
 
 
+# Check for libreadline
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -3713,8 +3682,8 @@ fi
 
 
 
+# Check for bigphysarea.
 
-echo check $DO_MAS_DRIVER $DRIVER_BIGPHYS
 if test "$DO_MAS_DRIVER" != "no" && test "$DRIVER_BIGPHYS" != "no"; then
 BIGPHYS_H=${KERNEL_DIR}/build/include/linux/bigphysarea.h
 as_ac_Header=`echo "ac_cv_header_$BIGPHYS_H" | $as_tr_sh`
@@ -3860,7 +3829,7 @@ fi
 
 
 
-if test "$DO_MAS_SWIG" != "no"; then
+if test "$PYTHON_DIR" != "no"; then
    # Extract the first word of "swig", so it can be a program name with args.
 set dummy swig; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -3899,12 +3868,151 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-   test "HAS_SWIG" != "yes" && \
+   test "$HAS_SWIG" != "yes" && \
       { { echo "$as_me:$LINENO: error: please install swig package or pass --without-python.
 See \`config.log' for more details." >&5
 echo "$as_me: error: please install swig package or pass --without-python.
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
+   as_ac_Header=`echo "ac_cv_header_$PYTHON_DIR/Python.h" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $PYTHON_DIR/Python.h" >&5
+echo $ECHO_N "checking for $PYTHON_DIR/Python.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $PYTHON_DIR/Python.h usability" >&5
+echo $ECHO_N "checking $PYTHON_DIR/Python.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$PYTHON_DIR/Python.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $PYTHON_DIR/Python.h presence" >&5
+echo $ECHO_N "checking $PYTHON_DIR/Python.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$PYTHON_DIR/Python.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $PYTHON_DIR/Python.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $PYTHON_DIR/Python.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $PYTHON_DIR/Python.h" >&5
+echo $ECHO_N "checking for $PYTHON_DIR/Python.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: could not find Python.h; perhaps you want --with-python=... or you need to install python-dev
+See \`config.log' for more details." >&5
+echo "$as_me: error: could not find Python.h; perhaps you want --with-python=... or you need to install python-dev
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 fi
 
 
@@ -4584,11 +4692,11 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
 LN_S!$LN_S$ac_delim
-HAS_INSTALLX!$HAS_INSTALLX$ac_delim
 DO_MAS_DRIVER!$DO_MAS_DRIVER$ac_delim
 DRIVER_BIGPHYS!$DRIVER_BIGPHYS$ac_delim
 DRIVER_FAKEMCE!$DRIVER_FAKEMCE$ac_delim
 KERNEL_DIR!$KERNEL_DIR$ac_delim
+PYTHON_DIR!$PYTHON_DIR$ac_delim
 DO_MAS_SWIG!$DO_MAS_SWIG$ac_delim
 MAS_USER!$MAS_USER$ac_delim
 MAS_GROUP!$MAS_GROUP$ac_delim
@@ -5605,11 +5713,11 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
 LN_S!$LN_S$ac_delim
-HAS_INSTALLX!$HAS_INSTALLX$ac_delim
 DO_MAS_DRIVER!$DO_MAS_DRIVER$ac_delim
 DRIVER_BIGPHYS!$DRIVER_BIGPHYS$ac_delim
 DRIVER_FAKEMCE!$DRIVER_FAKEMCE$ac_delim
 KERNEL_DIR!$KERNEL_DIR$ac_delim
+PYTHON_DIR!$PYTHON_DIR$ac_delim
 DO_MAS_SWIG!$DO_MAS_SWIG$ac_delim
 MAS_USER!$MAS_USER$ac_delim
 MAS_GROUP!$MAS_GROUP$ac_delim
@@ -6627,11 +6735,11 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
 LN_S!$LN_S$ac_delim
-HAS_INSTALLX!$HAS_INSTALLX$ac_delim
 DO_MAS_DRIVER!$DO_MAS_DRIVER$ac_delim
 DRIVER_BIGPHYS!$DRIVER_BIGPHYS$ac_delim
 DRIVER_FAKEMCE!$DRIVER_FAKEMCE$ac_delim
 KERNEL_DIR!$KERNEL_DIR$ac_delim
+PYTHON_DIR!$PYTHON_DIR$ac_delim
 DO_MAS_SWIG!$DO_MAS_SWIG$ac_delim
 MAS_USER!$MAS_USER$ac_delim
 MAS_GROUP!$MAS_GROUP$ac_delim
@@ -7650,11 +7758,11 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
 LN_S!$LN_S$ac_delim
-HAS_INSTALLX!$HAS_INSTALLX$ac_delim
 DO_MAS_DRIVER!$DO_MAS_DRIVER$ac_delim
 DRIVER_BIGPHYS!$DRIVER_BIGPHYS$ac_delim
 DRIVER_FAKEMCE!$DRIVER_FAKEMCE$ac_delim
 KERNEL_DIR!$KERNEL_DIR$ac_delim
+PYTHON_DIR!$PYTHON_DIR$ac_delim
 DO_MAS_SWIG!$DO_MAS_SWIG$ac_delim
 MAS_USER!$MAS_USER$ac_delim
 MAS_GROUP!$MAS_GROUP$ac_delim
